### ISSUE TITLE
What is the proper way to run this?

### ISSUE THREAD

**Issue by Aneeshers** [taznux/lung-image-analysis#8]
Hi I'm just a Matlab hobbyist, this project seemed very interesting, I'm just wondering what the proper way is to run this project.

Thanks

**Comment by taznux** [comment]
Hi Aneeshers,

This is a framework for nodule detection and lung image analysis. I have three test code for nodule detection, image convert, and nodule segmentation.

Before you run this, you should have a recent version of MATLAB (after 2013b) because of the table datatype. http://blogs.mathworks.com/loren/2013/09/10/introduction-to-the-new-matlab-data-types-in-r2013b/
And you should have a part or entire LIDC-IDRI database on your disk. 
> path_data = [pwd '/DATA/LIDC-IRDI']; %dcm files directory

**main.m**: Simple nodule detection system which has limited accuracy

**main_image_to_nrrd.m**: DICOM to nrrd converter (main_image_to_nrrd.m) for connection to my another image processing framework (https://github.com/taznux/radiomics-tools).
This code has different data path. I'll make a consistent path for next revision.
> path_data` = [pwd '/../../LIDC-IDRI/DOI/']; %dcm files directory

**main_nodule_segmentation.m**: Simple evaluation framework for nodule segmentation.

I'll update README.md with usages soon.

Thanks,
Wookjin

**Comment by Aneeshers** [comment]
@taznux  HI thank you so much, I just have another issue/question
So when I run the program I inputted a small file with about 133 dicom files,
then I get the error

```
error: matrix cannot be indexed with .
error: called from
    main at line 207 column 1
error: evaluating argument list element number 1
error: called from
    main at line 207 column 1
```

**Comment by taznux** [comment]
You cannot run this code on Octave. You have to use MATLAB 2013b or late version.

**Comment by Aneeshers** [comment]
@taznux Thank you, I will try it on MATLAB, any reason specifically why it won't function on GNU octave?

**Comment by taznux** [comment]
Even though they have similar syntax, they are different. These links can give you the answers.

https://en.wikibooks.org/wiki/MATLAB_Programming/Differences_between_Octave_and_MATLAB
http://stackoverflow.com/questions/12084246/differences-between-octave-and-matlab
